kamel: [Silverstone-x] py3 fix for platform_sensors
Fixes:

```
(vrf:mgmt)bluecmd@ixp-lab-sw2:~$ show environment
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +38.0 C  (high = +83.0 C, crit = +105.0 C)
Core 0:        +38.0 C  (high = +83.0 C, crit = +105.0 C)
Core 1:        +38.0 C  (high = +83.0 C, crit = +105.0 C)
Core 2:        +38.0 C  (high = +83.0 C, crit = +105.0 C)
Core 3:        +38.0 C  (high = +83.0 C, crit = +105.0 C)

Traceback (most recent call last):
  File "/usr/bin/platform_sensors.py", line 172, in <module>
    main()
  File "/usr/bin/platform_sensors.py", line 165, in main
    output_string += read_temperature_sensors(ipmi_sdr_elist)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/platform_sensors.py", line 92, in read_temperature_sensors
    reading = get_reading_by_name(sensor[0],ipmi_sdr_elist)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/platform_sensors.py", line 52, in get_reading_by_name
    for line in sdr_elist_dump.split("\n"):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```